/**
 * Flight Data
 * 8 flights for May 2-3, 2026.
 */

// variabel ini dibaca langsung oleh flights.js — makanya file ini harus diload lebih dulu di HTML
// urutan script tag di HTML: flights-data.js dulu, baru flights.js
const allFlightsData = [
  // ---- May 2, 2026 ----
  // setiap objek = satu penerbangan, propertinya nanti dipanggil satu per satu di flights.js saat render card
  {
    id: 1, // dipakai sebagai pengenal unik saat user klik "Book Now" — flights.js cari flight berdasarkan id ini
    airline: "Qatar Airways",
    logo: "https://img.favpng.com/10/19/15/qatar-airways-logo-airline-oryx-png-favpng-zzxmSycnu1dVBAvCSCDZEpwGU.jpg",
    flightNumber: "QR945",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png", // url bendera negara asal, ditampilkan di card
    destination: "Indonesia", // nilai ini yang dicocokkan saat user filter destinasi
    destinationCode: "CGK",
    destinationFlag: "https://flagcdn.com/w40/id.png",
    departureTime: "02:15",
    arrivalTime: "03:05",
    durationMinutes: 110, // disimpan dalam menit, nanti dikonversi ke "1h 50m" oleh flights.js
    pricePerPerson: 320, // harga dasar economy — booking.js kalikan ini dengan jumlah penumpang dan multiplier kelas
    date: "2026-05-02", // format YYYY-MM-DD, harus sama persis dengan nilai dari date input HTML agar filter cocok
  },
  {
    id: 2,
    airline: "Qatar Airways",
    logo: "https://img.favpng.com/10/19/15/qatar-airways-logo-airline-oryx-png-favpng-zzxmSycnu1dVBAvCSCDZEpwGU.jpg",
    flightNumber: "QR908",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Australia",
    destinationCode: "SYD",
    destinationFlag: "https://flagcdn.com/w40/au.png",
    departureTime: "20:30",
    arrivalTime: "06:15",
    durationMinutes: 465,
    pricePerPerson: 950,
    date: "2026-05-02",
  },
  {
    id: 3,
    airline: "Singapore Airlines",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png",
    flightNumber: "SQ950",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Indonesia",
    destinationCode: "CGK",
    destinationFlag: "https://flagcdn.com/w40/id.png",
    departureTime: "07:20",
    arrivalTime: "08:05",
    durationMinutes: 105,
    pricePerPerson: 350,
    date: "2026-05-02",
  },
  {
    id: 4,
    airline: "Singapore Airlines",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png",
    flightNumber: "SQ231",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Australia",
    destinationCode: "SYD",
    destinationFlag: "https://flagcdn.com/w40/au.png",
    departureTime: "00:45",
    arrivalTime: "10:25",
    durationMinutes: 460,
    pricePerPerson: 1100,
    date: "2026-05-02",
  },
  // ---- May 3, 2026 ----
  // struktur identik dengan May 2, hanya id, flightNumber, waktu, dan harga yang berbeda
  {
    id: 5,
    airline: "Qatar Airways",
    logo: "https://img.favpng.com/10/19/15/qatar-airways-logo-airline-oryx-png-favpng-zzxmSycnu1dVBAvCSCDZEpwGU.jpg",
    flightNumber: "QR947",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Indonesia",
    destinationCode: "CGK",
    destinationFlag: "https://flagcdn.com/w40/id.png",
    departureTime: "21:00",
    arrivalTime: "21:50",
    durationMinutes: 110,
    pricePerPerson: 310,
    date: "2026-05-03",
  },
  {
    id: 6,
    airline: "Qatar Airways",
    logo: "https://img.favpng.com/10/19/15/qatar-airways-logo-airline-oryx-png-favpng-zzxmSycnu1dVBAvCSCDZEpwGU.jpg",
    flightNumber: "QR910",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Australia",
    destinationCode: "SYD",
    destinationFlag: "https://flagcdn.com/w40/au.png",
    departureTime: "23:45",
    arrivalTime: "09:30",
    durationMinutes: 465,
    pricePerPerson: 920,
    date: "2026-05-03",
  },
  {
    id: 7,
    airline: "Singapore Airlines",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png",
    flightNumber: "SQ952",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Indonesia",
    destinationCode: "CGK",
    destinationFlag: "https://flagcdn.com/w40/id.png",
    departureTime: "09:35",
    arrivalTime: "10:25",
    durationMinutes: 110,
    pricePerPerson: 380,
    date: "2026-05-03",
  },
  {
    id: 8,
    airline: "Singapore Airlines",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png",
    flightNumber: "SQ211",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Australia",
    destinationCode: "SYD",
    destinationFlag: "https://flagcdn.com/w40/au.png",
    departureTime: "10:30",
    arrivalTime: "20:15",
    durationMinutes: 465,
    pricePerPerson: 1050,
    date: "2026-05-03",
  },
];
