/**
 * Flight Data
 * 8 flights for May 2-3, 2026.
 */

const allFlightsData = [
  // May 2, 2026
  {
    id: 1,
    airline: "Qatar Airways",
    logo: "https://img.favpng.com/10/19/15/qatar-airways-logo-airline-oryx-png-favpng-zzxmSycnu1dVBAvCSCDZEpwGU.jpg",
    flightNumber: "QR945",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Indonesia",
    destinationCode: "CGK",
    destinationFlag: "https://flagcdn.com/w40/id.png",
    departureTime: "02:15",
    arrivalTime: "03:05",
    durationMinutes: 110,
    pricePerPerson: 320,
    date: "2026-05-02",
  },
  {
    id: 2,
    airline: "Qatar Airways",
    logo: "https://img.favpng.com/10/19/15/qatar-airways-logo-airline-oryx-png-favpng-zzxmSycnu1dVBAvCSCDZEpwGU.jpg",
    flightNumber: "QR908",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Australia",
    destinationCode: "SYD",
    destinationFlag: "https://flagcdn.com/w40/au.png",
    departureTime: "20:30",
    arrivalTime: "06:15",
    durationMinutes: 465,
    pricePerPerson: 950,
    date: "2026-05-02",
  },
  {
    id: 3,
    airline: "Singapore Airlines",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png",
    flightNumber: "SQ950",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Indonesia",
    destinationCode: "CGK",
    destinationFlag: "https://flagcdn.com/w40/id.png",
    departureTime: "07:20",
    arrivalTime: "08:05",
    durationMinutes: 105,
    pricePerPerson: 350,
    date: "2026-05-02",
  },
  {
    id: 4,
    airline: "Singapore Airlines",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png",
    flightNumber: "SQ231",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Australia",
    destinationCode: "SYD",
    destinationFlag: "https://flagcdn.com/w40/au.png",
    departureTime: "00:45",
    arrivalTime: "10:25",
    durationMinutes: 460,
    pricePerPerson: 1100,
    date: "2026-05-02",
  },
  // May 3, 2026
  {
    id: 5,
    airline: "Qatar Airways",
    logo: "https://img.favpng.com/10/19/15/qatar-airways-logo-airline-oryx-png-favpng-zzxmSycnu1dVBAvCSCDZEpwGU.jpg",
    flightNumber: "QR947",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Indonesia",
    destinationCode: "CGK",
    destinationFlag: "https://flagcdn.com/w40/id.png",
    departureTime: "21:00",
    arrivalTime: "21:50",
    durationMinutes: 110,
    pricePerPerson: 310,
    date: "2026-05-03",
  },
  {
    id: 6,
    airline: "Qatar Airways",
    logo: "https://img.favpng.com/10/19/15/qatar-airways-logo-airline-oryx-png-favpng-zzxmSycnu1dVBAvCSCDZEpwGU.jpg",
    flightNumber: "QR910",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Australia",
    destinationCode: "SYD",
    destinationFlag: "https://flagcdn.com/w40/au.png",
    departureTime: "23:45",
    arrivalTime: "09:30",
    durationMinutes: 465,
    pricePerPerson: 920,
    date: "2026-05-03",
  },
  {
    id: 7,
    airline: "Singapore Airlines",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png",
    flightNumber: "SQ952",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Indonesia",
    destinationCode: "CGK",
    destinationFlag: "https://flagcdn.com/w40/id.png",
    departureTime: "09:35",
    arrivalTime: "10:25",
    durationMinutes: 110,
    pricePerPerson: 380,
    date: "2026-05-03",
  },
  {
    id: 8,
    airline: "Singapore Airlines",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Singapore_Airlines_Logo_2.svg/250px-Singapore_Airlines_Logo_2.svg.png",
    flightNumber: "SQ211",
    origin: "Singapore",
    originCode: "SIN",
    originFlag: "https://flagcdn.com/w40/sg.png",
    destination: "Australia",
    destinationCode: "SYD",
    destinationFlag: "https://flagcdn.com/w40/au.png",
    departureTime: "10:30",
    arrivalTime: "20:15",
    durationMinutes: 465,
    pricePerPerson: 1050,
    date: "2026-05-03",
  },
];
